### ISSUE TITLE
The fibonacci sequence is wrong.

### ISSUE THREAD

**Issue by lewisdiamond** [saschpe/PlanningPoker#2]
Rename the current "fibonacci" sequence to something else because it's not a fibonacci sequence.

https://en.wikipedia.org/wiki/Fibonacci_number

It reads `0 1/2 1 2 3 5 8 13 20 40 100 ? @`
while it should read `0 1 2 3 5 8 13 21 34 55 89... ? @` (I'd add infinity)

I also suggest adding an actual fibonacci sequence.

**Comment by saschpe** [comment]
https://pm.stackexchange.com/questions/9851/why-do-scrum-user-stories-only-use-the-fibonacci-series#9857

**Comment by lewisdiamond** [comment]
You can't just call `0 1/2 1 2 3 5 8 13 20 40 100` a fibonacci squence. It's just not. Rename it. Don't add an actual fibonacci sequence if you don't want, I don't care. Last I checked `13+8=21`, not `20`.
