### ISSUE TITLE
Add powers-of-two card deck

### ISSUE THREAD

**Issue by justindbelanger** [saschpe/PlanningPoker#5]
Hi,
My team and I use an exponential system of powers of two for story pointing, and I was wondering if that could be added to the list of card decks.

Thanks for making a solid and useful app!

**Comment by saschpe** [comment]
What would be the value domain? From 1,2,...,32?

**Comment by justindbelanger** [comment]
Yeah, from 2^0 to 2^4 (1..16), perhaps with a ? for "unknown", would be perfect!
